module.exports = {
    extends: [
        './js',
        'plugin:vue/recommended',
    ],
    parser: 'vue-eslint-parser',
    rules: {
        'vue/no-dupe-keys': 'error',
        'vue/no-reserved-keys': 'error',
        'vue/no-shared-component-data': 'error',
        'vue/require-valid-default-prop': 'error',
        'vue/require-default-prop': 'error',
        'vue/require-prop-types': 'error',
        'vue/this-in-template': 'error',
        'vue/return-in-computed-property': 'error',
        'vue/html-quotes': 'error',
        'vue/order-in-components': [2, {
            'order': [
                ['name', 'delimiters', 'functional', 'extends'],
                'el',
                'template',
                ['components', 'directives', 'filters'],
                ['parent', 'mixins', 'provide', 'inject'],
                'model',
                'props',
                'propsData',
                'data',
                'chill',
                'computed',
                'watch',
                'methods',
                'LIFECYCLE_HOOKS',
                'render',
                'renderError',
            ],
        }],
        'vue/max-attributes-per-line': [2, {
            'singleline': 2,
            'multiline': {
                'max': 1,
                'allowFirstLine': false,
            },
        }],
        'vue/html-self-closing': ['error', {
            'html': {
                'void': 'never',
                'normal': 'never',
                'component': 'never',
            },
        }],
        'vue/html-closing-bracket-newline': ['error', {
            'singleline': 'never',
            'multiline': 'always',
        }],
        'vue/html-indent': ['error', 4],
        'vue/no-side-effects-in-computed-properties': ['off'],
        'vue/attributes-order': ['off'],
        'vue/prop-name-casing': ['error', 'camelCase'],
        'vue/multiline-html-element-content-newline': ['off'],
        'vue/singleline-html-element-content-newline': ['off'],
        'vue/no-v-html': ['off'],
        'vue/require-component-is': ['off'],
    },
};
